spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_auth_db
    username: root
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: "TelegramBot"

localtunnel:
  port: 8080
  subdomain: myapp123

server:
  port: 8080
  ssl:
    enabled: false